### ISSUE TITLE
Http Request causes UE4 to crash!

### ISSUE THREAD

**Issue by lAvArt** [RLoris/HttpHelperDoc#1]
Hi,

I'm facing this problem when using HTTP Helper Plugin that's causing Unreal to crash. I tried to submit a form but it won't accept the https://blueprintue.com URL. So, I thought it might be helpful to post it here. The issue is as follows:

Whenever I try to send multiple Http Requests based on different URL's using a string array and for each loop, UE4 crashes with the error Code:

```
Assertion failed: IsValid() [File:D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Templates/SharedPointer.h] [Line: 890]

UE4Editor_Core
UE4Editor_Core
UE4Editor_HttpHelper!<lambda_d734c0c66779fb748b1875166d82ab90>::operator()() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\HttpHelper\Source\HttpHelper\Private\HttpRequest.cpp:130]
UE4Editor_HttpHelper!TBaseFunctorDelegateInstance<void __cdecl(TSharedPtr<IHttpRequest,1>,int,int),FDefaultDelegateUserPolicy,<lambda_d734c0c66779fb748b1875166d82ab90> >::ExecuteIfSafe() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:836]
UE4Editor_HTTP
UE4Editor_HTTP
UE4Editor_HTTP
UE4Editor_HTTP
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll
```

Here's a link to the blueprintue.com:

https://blueprintue.com/render/jl2g4z_b/

It's much appreciated if you help solve the problem.

Thanks.

**Comment by RLoris** [comment]
Hi, 

Can you please submit the issue form again but this time with a valid URL link with this format https://blueprintue.com/blueprint/{code}, that's why the form was not valid, I can't access your blueprint with the link you provided me !

I will look into that issue as soon as you do this

Thanks

**Comment by lAvArt** [comment]
I just submitted the form.
Thanks for Helping.

**Comment by RLoris** [comment]
Hey Received ! but your blueprint URL link seems private I can't access it

**Comment by lAvArt** [comment]
Yeah, sorry about that.
Could you check again please?

**Comment by RLoris** [comment]
Perfect ! it works now

**Comment by lAvArt** [comment]
Great! Btw, the "CheckURL" event is being called from websocket "On text Message" after evaluating Result Text Message, and Websocket is initialized at Event BeginPlay.
I'm not sure this is relevant but I think it might be useful to get a better understanding of the whole setup.

**Comment by RLoris** [comment]
Regarding your multi URL call issue, you cannot use a for loop to make multiple URL call like this. Because every time the loop calls the AsyncHttp node, it will cancel the previous call and make the new one, it's better to use this approach and make them sequential like this: https://blueprintue.com/blueprint/1xsxk9kg/ Try this and tell me if it works for you ! A for loop execute itself very fast and does not wait for AsyncHttp node to finish because it's Async... thus cancelling your request every time, you should make an event driven sequential call like the one I show you above, when the first call is completed or failed, proceed with the next one and voila ! You should perhaps add a Boolean value IsCallInProgress to avoid calling checkUrl multiple time and cancel the request again and why not use a queue when a call is in progress, place the URL in a queue and once a request is done, go to the next queue element and empty it like that.

**Comment by lAvArt** [comment]
That seems to have solved the problem! I really appreciate your help.
I think adding a Boolean value IsCallInProgress could be based on the "Is Finished" HttpResponse pin as well!
As for the queuing suggestion, it might be a better way to handle the requests but I'm not sure how you'd go with this approach.

In any case, thanks again for your help and quick reply.

**Comment by RLoris** [comment]
Glad to hear that ! I will be closing this issue, I will still investigate about the crash to avoid that even if you call the node in a loop. Good luck with your project and thanks for using this plugin !

PS: An improved version would be to have a branch before the AsyncHttp node that checks if a call is in progress, if it is the case add the url to an array (queue) and do nothing else, if it is not the case and no call is in progress then call the node and then set IsCallInProgress to true, then in the completed or failed delegate you would need to set IsCallInProgress to false again and also check the queue for the next element that you remove and call CheckUrl(NewUrl). So you should get rid of the idx system and directly pass a string (url) to the function and that way you could use a for loop and pass each string to the CheckUrl(Array[Idx]) and it will execute them sequentially based on a queue system.
